apiVersion: v1
kind: Secret
metadata:
  name: wordle-bot
type: Opaque
data:
  .env: |-
    <snip>
---
apiVersion: v1
kind: Service
metadata:
  name: wordle-bot
  namespace: default
  labels:
    app.kubernetes.io/name: wordle-bot
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app.kubernetes.io/name: wordle-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle-bot
  namespace: default
  labels:
    app.kubernetes.io/name: wordle-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordle-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordle-bot
    spec:
      volumes:
        - name: env
          secret:
            secretName: wordle-bot
            defaultMode: 0644
            items:
              - key: .env
                path: .env
      containers:
        - name: wordle-bot
          image: <snip>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
            - name: APP_ENV
              value: production
          volumeMounts:
            - name: env
              mountPath: "/var/app"
              readOnly: true
          livenessProbe:
            exec:
              command: ["node", "-v"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
